# Generated by Django 4.0.3 on 2022-04-07 05:22

import core.courses.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.courses.models.chapter_directory_path, verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.courses.models.chapter_directory_path, verbose_name='Video')),
                ('vimeo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vimeo Video ID (Optional)')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.courses.models.thumbnail_directory_path, verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.courses.models.thumbnail_directory_path, verbose_name='Video')),
                ('vimeo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vimeo Video ID (Optional)')),
                ('slug', models.SlugField(max_length=250, unique=True, unique_for_date='published', verbose_name='Slug')),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('authors', models.ManyToManyField(to='courses.author')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.courses.models.chapter_directory_path, verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to=core.courses.models.chapter_directory_path, verbose_name='Video')),
                ('vimeo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vimeo Video ID (Optional)')),
                ('content', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
