# Generated by Django 4.0.4 on 2022-04-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
