# Generated by Django 3.1.7 on 2021-02-28 23:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cat_name', max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, db_column='cat_description', max_length=500, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(db_column='cst_names', max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(db_column='cst_surnames', max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(db_column='cst_dni', max_length=10, unique=True, verbose_name='Fecha de Nacimiento')),
                ('date_birthday', models.DateField(db_column='cst_date_birthday', default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('address', models.CharField(blank=True, db_column='cst_address', max_length=150, null=True, verbose_name='Direccion')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], db_column='cst_gender', default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='pro_name', max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, db_column='pro_image', null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('pvp', models.DecimalField(db_column='pro_pvp', decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta')),
                ('category', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='erp.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(db_column='sal_date_joined', default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(db_column='sal_subtotal', decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(db_column='sal_iva', decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(db_column='sal_total', decimal_places=2, default=0.0, max_digits=9)),
                ('customer', models.ForeignKey(db_column='cst_id', on_delete=django.db.models.deletion.CASCADE, to='erp.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(db_column='sld_price', decimal_places=2, default=0.0, max_digits=9)),
                ('quantity', models.IntegerField(db_column='sld_quantity', default=0)),
                ('subtotal', models.DecimalField(db_column='sld_subtotal', decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='erp.product')),
                ('sale', models.ForeignKey(db_column='sal_id', on_delete=django.db.models.deletion.CASCADE, to='erp.sale')),
            ],
            options={
                'verbose_name': 'Sale Detail',
                'verbose_name_plural': 'Sales Details',
                'db_table': 'sales_details',
                'ordering': ['id'],
            },
        ),
    ]
