# Generated by Django 3.1.7 on 2021-03-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210228_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='iva',
            new_name='igv',
        ),
    ]
