# Generated by Django 3.1.7 on 2021-03-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210302_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='cst_id', on_delete=django.db.models.deletion.CASCADE, to='erp.customer'),
        ),
    ]
