# Generated by Django 3.1.7 on 2021-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210302_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_column='pro_stock', default=0, verbose_name='Stock'),
        ),
    ]
