# Generated by Django 4.0.3 on 2022-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sacks',
            new_name='Sack',
        ),
        migrations.AlterModelOptions(
            name='sack',
            options={'ordering': ['id'], 'verbose_name': 'Sack', 'verbose_name_plural': 'Sacks'},
        ),
        migrations.AlterField(
            model_name='bdi',
            name='q1',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='sack',
            table='sacks',
        ),
    ]
